# Generated by Django 4.1.5 on 2023-02-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_project_id_contributor_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('BE', 'Back-end'), ('FE', 'Front-end'), ('AD', 'Android'), ('IO', 'iOS')], max_length=4),
        ),
    ]
