# Generated by Django 4.1.5 on 2023-02-28 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tag', models.CharField(choices=[('BG', 'Bug'), ('IP', 'Improvement'), ('TD', 'Task')], max_length=4)),
                ('priority', models.CharField(choices=[('LW', 'Low'), ('MD', 'Medium'), ('HI', 'Hight')], max_length=4)),
                ('status', models.CharField(choices=[('TD', 'Todo'), ('OG', 'Ongoing'), ('CP', 'Completed')], max_length=4)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
